In [316]:
import pandas as pd

In [317]:
data = pd.read_csv("/home/samiransamanta/Python/Data Cleaning/Airbnb Data Cleaning/Airbnb_Open_Data.csv")
print(data)

             id                                              NAME  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                               NaN
4       1003689  Entire Apt: Spacious Studio/Loft by central park
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
2       78829239556                    NaN        Elise           Manhattan
3       85098326012            unconfirmed        Garry            Brooklyn
4       92037596077               verified       Lyndon           Manhattan
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country  ...  \
0                Kensington  40.64749 -73.97237  United States  ...
1                   Midtown  40.75362 -73.98377  United States  ...
2                    Harlem  40.80902 -73.94190  United States  ...
3              Clinton Hill  40.68514 -73.95976  United States  ...
4               East Harlem  40.79851 -73.94399  United States  ...
...                     ...       ...       ...            ...  ...
102594         Williamsburg  40.70862 -73.94651  United States  ...
102595  Morningside Heights  40.80460 -73.96545  United States  ...
102596           Park Slope  40.67505 -73.98045  United States  ...
102597     Long Island City  40.74989 -73.93777  United States  ...
102598      Upper West Side  40.76807 -73.98342  United States  ...

       service fee minimum nights number of reviews last review  \
0            $193            10.0               9.0  10/19/2021
1             $28            30.0              45.0   5/21/2022
2            $124             3.0               0.0         NaN
3             $74            30.0             270.0    7/5/2019
4             $41            10.0               9.0  11/19/2018
...            ...            ...               ...         ...
102594       $169             1.0               0.0         NaN
102595       $167             1.0               1.0    7/6/2015
102596       $198             3.0               0.0         NaN
102597       $109             2.0               5.0  10/11/2015
102598       $206             1.0               0.0         NaN

        reviews per month review rate number calculated host listings count  \
0                    0.21                4.0                            6.0
1                    0.38                4.0                            2.0
2                     NaN                5.0                            1.0
3                    4.64                4.0                            1.0
4                    0.10                3.0                            1.0
...                   ...                ...                            ...
102594                NaN                3.0                            1.0
102595               0.02                2.0                            2.0
102596                NaN                5.0                            1.0
102597               0.10                3.0                            1.0
102598                NaN                3.0                            1.0

        availability 365                                        house_rules  \
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
2                  352.0  I encourage you to use my kitchen, cooking and...
3                  322.0                                                NaN
4                  289.0  Please no smoking in the house, porch or on th...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                                NaN
102597             386.0                                                NaN
102598              69.0                                                NaN

       license
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
102594     NaN
102595     NaN
102596     NaN
102597     NaN
102598     NaN

[102599 rows x 26 columns]

/tmp/ipykernel_7309/992759773.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/home/samiransamanta/Python/Data Cleaning/Airbnb Data Cleaning/Airbnb_Open_Data.csv")

In [318]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB
None

In [319]:
print(data.columns)

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [320]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']

columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'id']

In [321]:
print("Length of keep column: ", len(columns_to_keep))

print("Length of drop column: ", len(columns_to_drop))

Length of keep column:  19
Length of drop column:  7

In [322]:
data_frame = data[columns_to_keep]

In [323]:
print("Original Data: ", data.shape)
print("Filtered Data: ", data_frame.shape)

Original Data:  (102599, 26)
Filtered Data:  (102599, 19)

### Droping columns

In [324]:
data.drop(columns= columns_to_drop, inplace=True)

In [325]:
data.shape

(102599, 19)

### Rename the columns

In [326]:
data.rename(columns={
    "NAME": "Name"
}, inplace=True)

In [327]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [328]:
new_column_name = []

for i in data.columns:
    new_column_name.append(i.upper())

In [329]:
new_dataframe_to_modify = data.copy()

In [330]:
new_dataframe_to_modify.columns = new_column_name

In [331]:
new_dataframe_to_modify.columns

Index(['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME',
       'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY',
       'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE',
       'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS',
       'NUMBER OF REVIEWS', 'LAST REVIEW'],
      dtype='object')

In [332]:
data.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [333]:
data.drop_duplicates(inplace=True)

In [334]:
data.duplicated().value_counts()

False    102058
Name: count, dtype: int64

In [335]:
data.isna().sum()

Name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
Construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

In [336]:
data.drop(columns=["last review"], inplace=True)

In [337]:
data.isna().sum()

Name                      250
host id                     0
host_identity_verified    289
host name                 404
neighbourhood group        29
neighbourhood              16
lat                         8
long                        8
country                   532
country code              131
instant_bookable          105
cancellation_policy        76
room type                   0
Construction year         214
price                     247
service fee               273
minimum nights            400
number of reviews         183
dtype: int64

In [338]:
data.dropna(inplace=True)

In [339]:
data.isna().sum()

Name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
Construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
dtype: int64

In [340]:
data["host_identity_verified"].str.upper()

0         UNCONFIRMED
1            VERIFIED
4            VERIFIED
5            VERIFIED
7         UNCONFIRMED
             ...
102029    UNCONFIRMED
102030       VERIFIED
102031       VERIFIED
102032    UNCONFIRMED
102040       VERIFIED
Name: host_identity_verified, Length: 99342, dtype: object

In [341]:
data["host_identity_verified"] = data["host_identity_verified"].str.upper()

In [342]:
data["host_identity_verified"]

0         UNCONFIRMED
1            VERIFIED
4            VERIFIED
5            VERIFIED
7         UNCONFIRMED
             ...
102029    UNCONFIRMED
102030       VERIFIED
102031       VERIFIED
102032    UNCONFIRMED
102040       VERIFIED
Name: host_identity_verified, Length: 99342, dtype: object

In [343]:
data["instant_bookable"]

0         False
1         False
4         False
5          True
7         False
          ...
102029    False
102030     True
102031     True
102032    False
102040     True
Name: instant_bookable, Length: 99342, dtype: object

### Make this True as 1 and False as 0

In [344]:
data["instant_bookable"].apply(lambda x: 1 if x == True else 0)

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: instant_bookable, Length: 99342, dtype: int64

In [345]:
data["instant_bookable"]

0         False
1         False
4         False
5          True
7         False
          ...
102029    False
102030     True
102031     True
102032    False
102040     True
Name: instant_bookable, Length: 99342, dtype: object

In [346]:
data['instant_bookable'] = data['instant_bookable'].apply(lambda x: 1 if x == True else 0)

In [347]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [348]:
# data['instant_bookable'][15]

### To fix this error we need to fix the indexing

In [349]:
data.reset_index(inplace=True)

In [350]:
type(data['instant_bookable'].iloc[15])

numpy.int64

In [351]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [352]:
type(data['price'][15])

str

### Make price type int

In [353]:
data['price']

0          $966
1          $142
2          $204
3          $577
4        $1,060
          ...
99337      $822
99338      $455
99339    $1,078
99340      $103
99341      $982
Name: price, Length: 99342, dtype: object

In [354]:
data['price'] = data['price'].str.replace("$", "")

In [355]:
data['price']

0          966
1          142
2          204
3          577
4        1,060
          ...
99337      822
99338      455
99339    1,078
99340      103
99341      982
Name: price, Length: 99342, dtype: object

In [356]:
data['price'] = data['price'].str.replace(",", "")

In [357]:
data['price']

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: price, Length: 99342, dtype: object

In [358]:
data['price'][15]

'1020 '

### Also remove the space " "

In [359]:
data["price"] = data['price'].str.replace(" ", "")

In [360]:
data["price"][15]

'1020'

In [361]:
data['price'].astype(int)

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: price, Length: 99342, dtype: int64

In [362]:
data['price'] = data['price'].astype(int)

In [363]:
type(data['price'][15])

numpy.int64

In [364]:
data.to_csv("Cleaned_Data.csv")

In [366]:
data = pd.read_csv("Cleaned_Data.csv")

data.drop(columns=["index"], inplace=True)

In [367]:
data.to_csv("Data_Without_Index.csv", index=False)

In [368]:
pd.read_csv("Data_Without_Index.csv")

,Unnamed: 0,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
3,3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,$115,3.0,74.0
4,4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,$164,1.0,9.0
99338,99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,$91,4.0,36.0
99339,99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,$216,1.0,58.0
99340,99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,$21,7.0,40.0
99341,99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0

In [370]:
%pip install openpyxl

data.to_excel("Excel_Cleanded_Data.xlsx", index=False)

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [371]:
pd.read_excel("Excel_Cleanded_Data.xlsx")

,Unnamed: 0,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966,$193,10,9
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,142,$28,30,45
2,2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,204,$41,10,9
3,3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013,577,$115,3,74
4,4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,1060,$212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018,822,$164,1,9
99338,99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015,455,$91,4,36
99339,99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020,1078,$216,1,58
99340,99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007,103,$21,7,40
99341,99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022,982,$196,1,239